# Generated by Django 5.1.6 on 2025-03-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_mp4_path', models.CharField(max_length=500)),
                ('mp4_path', models.CharField(max_length=500)),
                ('cover_path', models.CharField(max_length=500)),
                ('tag1', models.CharField(blank=True, max_length=100, null=True)),
                ('tag2', models.CharField(blank=True, max_length=100, null=True)),
                ('tag3', models.CharField(blank=True, max_length=100, null=True)),
                ('tag4', models.CharField(blank=True, max_length=100, null=True)),
                ('tag5', models.CharField(blank=True, max_length=100, null=True)),
                ('tag_string', models.CharField(blank=True, max_length=500, null=True)),
                ('numeric_id', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
