# Generated by Django 5.1.6 on 2025-03-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoasset',
            name='original_cover_path',
            field=models.CharField(default='static/null', max_length=500),
            preserve_default=False,
        ),
    ]
