# Generated by Django 5.1.7 on 2025-04-14 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalpose', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeric_id', models.CharField(max_length=10, unique=True)),
                ('key_angles', models.JSONField()),
                ('normalization_joints', models.JSONField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Configuration',
                'verbose_name_plural': 'Video Configurations',
            },
        ),
    ]
